# Generated by Django 5.0.1 on 2024-01-27 12:27

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createda_at', models.DateField(default=datetime.date.today, editable=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=15)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('createda_at', models.DateField(default=datetime.date.today, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createda_at', models.DateField(default=datetime.date.today, editable=False)),
                ('name', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organogram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=20, unique=True)),
                ('level', models.IntegerField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('createda_at', models.DateField(default=datetime.date.today, editable=False)),
                ('parent_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolAdmin.organogram')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createda_at', models.DateField(default=datetime.date.today, editable=False)),
                ('surname', models.CharField(max_length=15)),
                ('middlename', models.CharField(max_length=15)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('phonenumber', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('organogram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolAdmin.organogram')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('createda_at', models.DateField(default=datetime.date.today, editable=False)),
                ('departments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolAdmin.departments')),
            ],
        ),
    ]
