# Generated by Django 5.0.1 on 2024-01-26 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=15)),
                ('middlename', models.CharField(max_length=15)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('position', models.CharField(max_length=15)),
                ('phonenumber', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
