# Generated by Django 5.0.1 on 2024-01-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolAdmin', '0002_staff_employmentcode_staff_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='organogram',
        ),
        migrations.AddField(
            model_name='staff',
            name='organogram',
            field=models.ManyToManyField(related_name='staff_position', to='schoolAdmin.organogram'),
        ),
    ]
