# Generated by Django 5.0.1 on 2024-01-28 14:58

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolAdmin', '0004_alter_staff_middlename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=10)),
                ('starts', models.DateField(default=datetime.date(2024, 1, 28))),
                ('ends', models.DateField(default=datetime.date(2024, 1, 28))),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolAdmin.academicsession')),
            ],
        ),
    ]
