# Generated by Django 5.0.1 on 2024-01-29 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schoolAdmin', '0006_alter_academicsession_createda_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organogram',
            name='permission',
            field=models.ManyToManyField(related_name='organogram', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='staff',
            name='permission',
            field=models.ManyToManyField(related_name='staff_user', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user_login',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
