# Generated by Django 5.0.1 on 2024-01-25 18:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=15)),
                ('middlename', models.CharField(max_length=15)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('employmentCode', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('unit', models.IntegerField(default=1)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment', models.IntegerField(default=10)),
                ('CA_Test', models.IntegerField(default=20)),
                ('Exam', models.IntegerField(default=60)),
                ('attendance', models.IntegerField(default=10)),
                ('total', models.IntegerField(default=100, editable=False)),
                ('weight', models.IntegerField(default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.teacher')),
            ],
        ),
    ]
