# Generated by Django 5.0.1 on 2024-01-27 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
        ('schoolAdmin', '0002_staff_employmentcode_staff_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='employmentCode',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='organogram',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='surname',
        ),
        migrations.AddField(
            model_name='teacher',
            name='staff',
            field=models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='schoolAdmin.staff'),
        ),
    ]
