# Generated by Django 5.0.1 on 2024-01-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_remove_teacher_address_remove_teacher_employmentcode_and_more'),
        ('schoolAdmin', '0004_alter_staff_middlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='teachers', to='schoolAdmin.classes'),
        ),
    ]
