# Generated by Django 5.0.1 on 2024-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0004_remove_subject_teacher_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(related_name='teachersubject', to='lecturers.subject'),
        ),
    ]
