# Generated by Django 5.0.1 on 2024-01-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0005_remove_teacher_subject_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
