# Generated by Django 5.0.1 on 2024-01-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0006_alter_subject_name'),
        ('schoolAdmin', '0005_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolAdmin.term'),
        ),
        migrations.AddField(
            model_name='score',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolAdmin.term'),
        ),
        migrations.AddField(
            model_name='subject',
            name='term',
            field=models.ManyToManyField(null=True, related_name='term_subject', to='schoolAdmin.term'),
        ),
    ]
