# Generated by Django 5.0.1 on 2024-01-27 12:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturers', '__first__'),
        ('schoolAdmin', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=15)),
                ('middlename', models.CharField(max_length=15)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ParentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=15)),
                ('is_master', models.BooleanField(default=False)),
                ('is_sponsor', models.BooleanField(default=False)),
                ('guardians', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.guardian')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport', models.ImageField(null=True, upload_to='')),
                ('surname', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=15)),
                ('middlename', models.CharField(max_length=15)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('DateofBirth', models.DateField()),
                ('admission_no', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15, null=True)),
                ('addmission_status', models.CharField(choices=[('Admitted', 'Admitted'), ('Graduated', 'Graduated'), ('Prospective', 'Prospective')], default='Prospective', max_length=15)),
                ('guardian', models.ManyToManyField(through='students.ParentStudent', to='students.guardian')),
            ],
        ),
        migrations.AddField(
            model_name='parentstudent',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gradePercent', models.FloatField(default=0, editable=False)),
                ('gradeCGPA', models.FloatField(default=1, editable=False)),
                ('gradeAlpha', models.CharField(default='F', editable=False, max_length=2)),
                ('teacherRemarks', models.TextField()),
                ('principalRemarks', models.TextField()),
                ('is_available', models.BooleanField(default=False)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolAdmin.classes')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolAdmin.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectReg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolAdmin.classes')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolAdmin.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ManyToManyField(related_name='students', to='lecturers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment', models.JSONField(default=list)),
                ('CA_Test', models.JSONField(default=list, editable=False)),
                ('exams', models.JSONField(default=list, editable=False)),
                ('attendance', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0, editable=False)),
                ('point', models.FloatField(default=1, editable=False)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.score')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolAdmin.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subjectreg')),
            ],
        ),
    ]
