# Generated by Django 5.0.1 on 2024-01-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='middlename',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='middlename',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
