# Generated by Django 5.0.1 on 2024-01-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_guardian_middlename_alter_student_middlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='subject',
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
