# Generated by Django 5.0.1 on 2024-01-22 11:06

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_student_id_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='timeDate',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='CourseReg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=15)),
                ('course_code', models.CharField(max_length=10)),
                ('unit', models.IntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment', models.TextField()),
                ('CA_Test', models.TextField()),
                ('exams', models.TextField()),
                ('attendance', models.FloatField()),
                ('total_score', models.FloatField()),
                ('point', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
