# Generated by Django 5.0.1 on 2024-01-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_attendance_timedate_attendance_date_coursereg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='addmission_status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Graduated', 'Graduated'), ('Prospective', 'Prospective')], default='Prospective', max_length=15),
        ),
    ]
