# Generated by Django 5.0.1 on 2024-01-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_score_subject_alter_student_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='assignment',
            field=models.JSONField(default=list, editable=False),
        ),
    ]
