# Generated by Django 5.0.1 on 2024-01-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolAdmin', '0005_term'),
        ('students', '0004_alter_score_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolAdmin.term'),
        ),
    ]
