# Generated by Django 5.0.1 on 2024-01-25 19:21

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_score_ca_test_alter_score_assignment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseReg',
            new_name='SubjectReg',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 25, 19, 20, 27, 727764, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gradePercent', models.FloatField(default=0, editable=False)),
                ('gradeCGPA', models.FloatField(default=1, editable=False)),
                ('gradeAlpha', models.CharField(default='F', editable=False, max_length=2)),
                ('teacherRemarks', models.TextField()),
                ('principalRemarks', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
