# Generated by Django 5.0.1 on 2024-01-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_coursereg_subjectreg_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(editable=False),
        ),
    ]
